# Generated by Django 2.2.6 on 2019-10-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.TextField(max_length=20)),
                ('birthday', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
