# Generated by Django 2.2.6 on 2019-11-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('title_en', models.TextField(max_length=40)),
                ('audience', models.IntegerField(max_length=10)),
                ('open_date', models.DateField(auto_now=True)),
                ('genre', models.TextField(max_length=10)),
                ('watch_grade', models.TextField(max_length=8)),
                ('score', models.IntegerField(max_length=5)),
                ('poster_url', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
