# Generated by Django 2.2.7 on 2019-11-06 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_At',
            new_name='created_at',
        ),
    ]
